export const NOTE_CURSOR_STYLE = 'default'
export const CHECKBOX_CURSOR_STYLE = 'pointer'
export const NOTE_WAIT_CURSOR_STYLE = 'progress'
export const CHECKBOX_WAIT_CURSOR_STYLE = 'progress'

export const CURRENT_USER_SELECTOR = '#loggedas a'
export const ASSIGNED_USER_NAME_SELECTOR = '.assigned-to.attribute a'
export const NOTES_SELECTOR = '.journal.has-notes'
export const NOTES_EDIT_BTN_SELECTOR = '.contextual a.icon-edit'
export const NOTES_EDITOR_FORMAT_SELECTOR = '.pwfmt-format'
export const NOTE_TEXT_SELECTOR = '.wiki'
export const NOTE_HEADER = 'h4.note-header'
export const NOTE_HEADER_UPDATE_INFO_SELECTOR = 'h4.note-header span.update-info'
export const NOTE_CHECKBOXES_SELECTOR = '.wiki:not(.wiki-preview) input[type="checkbox"]'
export const PREVIEW_TAB_SELECTOR = '.tab-preview'
